import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
		<nav className="flex justify-between items-center p-4">
			<a href="/" className="text-xl">Home</a>
			<a href="/recipes" className="text-xl">Recipes</a>
			<a href="/shoppinglist" className="text-xl">Shopping List</a>
			<a href="/plan" className="text-xl">Plan</a>
			<a href="/login" className="text-xl">Login</a>
			<a href="/register" className="text-xl">Register</a>
			<a href="/logout" className="text-xl">Logout</a>
		</nav>
        {children}
      </body>
    </html>
  );
}
