# fly.toml app configuration file generated for dinner-droid-typesense on 2026-06-10T20:44:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dinner-droid-typesense'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile.typesense'

[env]
  NODE_ENV = 'production'

[[mounts]]
  source = 'typesense_data'
  destination = '/data'

[http_service]
  internal_port = 8108
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
